# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default=True, max_length=255)),
                ('url', models.CharField(default=True, max_length=255)),
                ('title', models.CharField(default=True, max_length=255)),
                ('keywords', models.CharField(default=True, max_length=255)),
                ('description', models.CharField(default=True, max_length=255)),
                ('description_unique', models.CharField(default=True, max_length=255)),
                ('title_unique', models.CharField(default=True, max_length=255)),
                ('h1', models.CharField(default=True, max_length=255)),
                ('h2', models.CharField(default=True, max_length=255)),
                ('vk', models.CharField(default=True, max_length=255)),
                ('facebook', models.CharField(default=True, max_length=255)),
                ('instagram', models.CharField(default=True, max_length=255)),
                ('broken_link', models.CharField(default=True, max_length=255)),
                ('date_add', models.DateField(blank=True)),
                ('yandex', models.CharField(default=True, max_length=255)),
                ('google', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SaveUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.IntegerField(choices=[(1, 'All site'), (2, 'One page')], default=1)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('identifier', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
    ]
